# Generated by Django 5.0.4 on 2024-04-09 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="System_User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
                ("age", models.IntegerField()),
                ("email", models.EmailField(max_length=254)),
                ("password", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Trips",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_position", models.IntegerField()),
                ("end_point", models.IntegerField()),
                ("status", models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name="Driver",
            fields=[
                (
                    "system_user_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="app.system_user",
                    ),
                ),
                ("driver_charges", models.IntegerField()),
            ],
            bases=("app.system_user",),
        ),
        migrations.CreateModel(
            name="Payments",
            fields=[
                (
                    "trip",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="app.trips",
                    ),
                ),
                ("amount", models.IntegerField()),
                ("Integer", models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name="vehicles",
            fields=[
                ("number_plate", models.CharField(max_length=255)),
                ("max_weight", models.IntegerField()),
                (
                    "driver",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="app.driver",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="trips",
            name="vehicle",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="app.vehicles"
            ),
        ),
    ]
